### ISSUE TITLE
wall stop scrolling when floaty appears

### ISSUE THREAD

**Issue by pmahmud** [410GameProgramming/LateToTheParty#1]
wall sometimes stop scrolling strangely when floaty appears

**Comment by jbrigleb** [comment]
I removed Floaty from the BlockSpawner and the wall scrolling issue still occurred. I'm going to assume they are unrelated, or at the very least, it doesn't have anything to the with Floaty object or scripts.

**Comment by pmahmud** [comment]
added a destroyer script and considering this to be closed!
