### ISSUE TITLE
wokky falls from his ground

### ISSUE THREAD

**Issue by pmahmud** [410GameProgramming/LateToTheParty#2]
wokky falls from his ground and becomes zombie

**Comment by jbrigleb** [comment]
I'm not yet sure why this is happening, but Wokkys aren't being destroyed by the destroyer, but their ground is, so the fall when they reach the destroyer.

**Comment by jbrigleb** [comment]
My assumption is that this is because the collider on the wokky is a gameobject childed to the wokky, rather than a component of the wokky object itself, so only the collider object is being destroyed, I'm going to start testing this now.

**Comment by jbrigleb** [comment]
This was not the problem, none of the Wokky child objects are being destroyed. When the BlockWithWokky reached the destroyer, only Pattern1 is destroyed. the Obstacle collider objects, and the Wokky are left completely intact.

**Comment by pmahmud** [comment]
fixed in the alpha build
